services:
  postgis:
    image: postgis/postgis:15-3.4
    hostname: postgis
    container_name: data-warehouse
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dop
    volumes:
      - ${PWD}/data_warehouse:/var/lib/postgresql/data
      - ${PWD}/config/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d dop" ]
      interval: 10s
      timeout: 5s
      retries: 5